image = "/store/swissai/a08/containers/4m/4m_image_decord.sqsh" # todi
# image = "/store/swissai/a08/containers/4m/4m_image_peft.sqsh" # todi
# image = "/capstor/store/cscs/swissai/a08/containers/4m/4m_image_peft.sqsh"
# image = "/capstor/store/cscs/swissai/a08/containers/4m/4m_image_bristen.sqsh" 
mounts = ["/capstor", "/users", "/store"] # for todi
# mounts = ["/capstor", "/users"]
 
writable = true
 
[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
NCCL_DEBUG = "INFO"
