image = "/store/swissai/a08/containers/4m/4m_image.sqsh"
 
mounts = ["/capstor", "/users", "/store"]
 
writable = true
 
[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
 
[env]
FI_CXI_DISABLE_HOST_REGISTER = "1"
FI_MR_CACHE_MONITOR = "userfaultfd"
NCCL_DEBUG = "INFO"
